Create table todo (ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
tuser varchar(30) NOT NULL,
tdesc varchar(100) NOT NULL,
tdate date NOT NULL,
isdone varchar(1) NOT NULL);

insert into todo values(default, 'narendra', 'learn writing quality coding', '2018-01-01', 'Y' );
insert into todo values(default, 'narendra', 'Hibernate with Spring MVC II', '2018-02-01', 'Y' );
insert into todo values(default, 'narendra', 'learn writing quality coding', '2018-03-01', 'N' );
insert into todo values(default, 'narendra', 'learn writing quality coding', '2018-04-01', 'N' );
